### ISSUE TITLE
Mf didn't read the right github link 💀

### ISSUE THREAD

**Issue by Jraylor** [NamelessSCP/CustomEscapes#3]
SCP-079 doesn't gain any EXP when SCP-049 kill targets / assist in kills. I believe this is the same case for SCP-106 too, however I'm rather sure he still works. Nonetheless, still worth a check.

_side note, hope you're doing alright nameless!_

**Comment by obvEve** [comment]
this is a plugin for changing escape roles... what the hell are you on about

**Comment by Jraylor** [comment]
Oh mf, I got wrong GitHub link im so dumb af 😭😭
